services:
  postgres:
    image: postgres:17-alpine
    container_name: payload_postgres_dev
    environment:
      POSTGRES_PASSWORD: localpassword
      POSTGRES_DB: richardkern-nz
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
